# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  def update_build_number
  	new_build_number = sh("date +'%s'")
    increment_build_number(
      build_number: new_build_number
    )
    return new_build_number
  end

  def ask_version_bump_type()
    if UI.interactive?
      bump_type = UI.select "Select Bump Type", %w{major minor patch none}
      if bump_type != "none"
        increment_version_number(bump_type: bump_type)
      end
    end
  end

  def match_all_type()
    match(type: "development")
    match(type: "appstore")
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    ask_version_bump_type()
    update_build_number()
    match_all_type()
    gym(
      workspace: "groov.xcworkspace",
      scheme: "groov",
      export_options: {
        method: "app-store",
        silent: true
      }
    )
    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t Aspera"
    testflight(skip_waiting_for_build_processing: true)
  end
end
